# .github/workflows/auto_commit.yml
name: Random Daily Commit

on:
  schedule:
    # Läuft 7-mal am Tag zu verschiedenen Zeiten (MEZ = UTC+1)
    - cron: "30 8 * * *"
    - cron: "50 9 * * *"
    - cron: "15 11 * * *"
    - cron: "40 12 * * *"
    - cron: "05 14 * * *"
    - cron: "20 15 * * *"
    - cron: "10 16 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository auschecken
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Zufallsentscheidung, ob ein Commit durchgeführt wird (Wahrscheinlichkeit 2 von 3)
    - name: Decide randomly to commit or not
      run: |
        # Erhöhe die Wahrscheinlichkeit des Abbruchs, z.B. nur 1 von 3 Läufen wird abgebrochen
        if [ $((RANDOM % 3)) -ne 0 ]; then
          echo "Skipping this run."
          exit 0
        fi

    # 3. Ändere die README.md-Datei (aktualisiere die letzte Zeile mit Datum und Uhrzeit im Format DDMM hh:mm)
    - name: Update last line of README file
      run: |
        # Setze die Zeitzone auf MEZ (Europe/Berlin)
        export TZ="Europe/Berlin"

        # Speichere den aktuellen Inhalt der README.md in einer temporären Datei
        temp_file=$(mktemp)
        
        # Entferne die letzte Zeile aus der README.md und speichere den Rest in der temporären Datei
        head -n -1 README.md > "$temp_file"
        
        # Füge das Datum und die Uhrzeit im Format DDMM hh:mm hinzu
        echo "###### Letztes Update: $(date +'%d%m %H:%M')" >> "$temp_file"
        
        # Ersetze die README.md mit dem neuen Inhalt
        mv "$temp_file" README.md

    # 4. Committe und pushe Änderungen
    - name: Commit and push changes
      run: |
        git config --global user.name "JANKEE92PL"
        git config --global user.email "jankee112@googlemail.com"
        git add README.md
        git commit -m "Automatisches Update am $(date +'%d%m %H:%M')"
        git pull --rebase
        git push
