# .github/workflows/auto_commit.yml
name: Random Daily Commit

on:
  schedule:
    # Läuft 10-mal am Tag zu verschiedenen Zeiten (UTC)
    - cron: "10 6 * * *"   # 06:10 UTC
    - cron: "30 7 * * *"   # 07:30 UTC
    - cron: "50 8 * * *"   # 08:50 UTC
    - cron: "15 10 * * *"  # 10:15 UTC
    - cron: "40 11 * * *"  # 11:40 UTC
    - cron: "05 13 * * *"  # 13:05 UTC
    - cron: "44 14 * * *"  # 14:44 UTC
    - cron: "35 15 * * *"  # 15:35 UTC
    - cron: "00 17 * * *"  # 17:00 UTC
    - cron: "25 19 * * *"  # 19:25 UTC

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository auschecken
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Zufallsentscheidung, ob ein Commit durchgeführt wird
    - name: Decide randomly to commit or not
      run: |
        # Generiere eine zufällige Zahl zwischen 0 und 1
        if [ $((RANDOM % 2)) -eq 0 ]; then
          echo "Skipping this run."
          exit 0
        fi

    # 3. Ändere die README.md-Datei (aktualisiere die letzte Zeile)
    - name: Update last line of README file
      run: |
        # Speichere den aktuellen Inhalt der README.md in einer temporären Datei
        temp_file=$(mktemp)
        
        # Entferne die letzte Zeile aus der README.md und speichere den Rest in der temporären Datei
        head -n -1 README.md > "$temp_file"
        
        # Füge die aktualisierte Zeile hinzu
        echo "###### Letztes Update: $(date)" >> "$temp_file"
        
        # Ersetze die README.md mit dem neuen Inhalt
        mv "$temp_file" README.md

    # 4. Committe und pushe Änderungen
    - name: Commit and push changes
      run: |
        git config --global user.name "JANKEE92PL"
        git config --global user.email "jankee112@googlemail.com"
        git add README.md
        git commit -m "Automatisches Update am $(date)"
        git pull --rebase
        git push
