# .github/workflows/auto_commit.yml
name: Daily Commit

# Festlegen des Zeitplans für die tägliche Ausführung um 10:45 MEZ (9:45 UTC)
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository auschecken
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Ändere die README.md-Datei (aktualisiere die letzte Zeile)
    - name: Update last line of README file
      run: |
        # Speichere den aktuellen Inhalt der README.md in einer temporären Datei
        temp_file=$(mktemp)
        
        # Entferne die letzte Zeile aus der README.md und speichere den Rest in der temporären Datei
        head -n -1 README.md > "$temp_file"
        
        # Füge die aktualisierte Zeile hinzu
        echo "<p color:"green">Letztes Update: *$(date)*</p>" >> "$temp_file"
        
        # Ersetze die README.md mit dem neuen Inhalt
        mv "$temp_file" README.md

    # 3. Änderungen committen und pushen
    - name: Commit and push changes
      run: |
        git config --global user.name "JANKEE92PL"
        git config --global user.email "jankee112@googlemail.com"
        git add README.md
        git commit -m "Automatisches Update am $(date)"
        git push
