# .github/workflows/auto_commit.yml
name: Daily Commit

# Festlegen des Zeitplans für die tägliche Ausführung um 12:00 UTC
on:
  schedule:
    - cron: "45 10 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository auschecken
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Ändere die README.md-Datei (Datum hinzufügen)
    - name: Update README file
      run: |
        echo "Letztes Update: $(date)" >> README.md

    # 3. Änderungen committen und pushen
    - name: Commit and push changes
      run: |
        git config --global user.name "JANKEE92PL"
        git config --global user.email "jankee112@googlemail.com"
        git add README.md
        git commit -m "Automatisches Update am $(date)"
        git push
